import React, { useState, useEffect } from "react";
import { Container } from "react-bootstrap";
import { useTranslation } from "react-i18next";
import { GlobalLoader } from "../../../../components";
import { ManageCmsServices } from "../../../../services/User/ManageCms/index.services";
import { logger, modalNotification, stringToHTML } from "../../../../utils";

function CookiesPolicy() {
  const [cookiesData, setCookiesData] = useState([]);
  const [loading, setLoading] = useState(false);
  const { t } = useTranslation();

  const getCookiesPolicyData = async () => {
    setLoading(true);
    try {
      let queryParams = { pageKey: "cookies_policy" };

      const res = await ManageCmsServices.commonServices({
        queryParams,
      });
      const { success, data, message } = res;
      if (success === 1) {
        setCookiesData(data?.pageContent);
      } else {
        modalNotification({
          type: "error",
          message,
        });
      }
    } catch (error) {
      logger(error);
    }
    setLoading(false);
  };
  useEffect(() => {
    getCookiesPolicyData();
  }, []);
  return (
    <>
      <section className="py-70">
        <Container>
          <div className="cmsPage">
            <div className="heading">
              <h3 className="heading_sub font-ad">
                {" "}
                {t("text.common.agreement")}
              </h3>
              <h1 className="heading_main">
                {" "}
                {t("text.cookiesPolicy.pageTitle")}
              </h1>
            </div>
            <div className="cmsPage">
              {loading ? (
                <GlobalLoader />
              ) : cookiesData?.length > 0 ? (
                <p>{stringToHTML(cookiesData)}</p>
              ) : (
                <p className="text-center noRecord mb-0">
                  {" "}
                  {t("text.common.noRecord")}
                </p>
              )}

              {/* <div className="static-page p-30 bg-850 radius-20">
          {loading ? (
            <GlobalLoader />
          ) : aboutUsData?.description?.length > 0 ? (
            <p>{stringToHTML(aboutUsData?.description)}</p>
          ) : (
            <p className="text-center noRecord mb-0">
              {t("text.sellerManageCms.noRecordFound")}
            </p>
          )}
      </div> */}
              {/* <ol>
                <li>
                  <p>
                    This mobile application and other related documentation are
                    licensed by Daakia Private Ltd. and/or its affiliates
                    (“DPL”, “Company”, “we” or “us”), having office at
                    ________________, to use only to the user (“you / your”) who
                    access or download or avail the Application in accordance
                    with the terms of this End User License Agreement (“EULA”).
                  </p>
                </li>
                <li>
                  <p>
                    This EULA is an electronic record under Information
                    Technology Act, 2000 and the rules there under as applicable
                    and as amended time to time pertaining to electronic records
                    under applicable Indian laws. This electronic record is
                    generated by a computer system and does not require any
                    physical or digital signatures. This is a binding agreement
                    between Daakia Private Ltd. (“DPL” or “Company” or “us” or
                    “we”) and you.
                  </p>
                </li>
                <li>
                  <p>
                    BY DOWNLOADING THIS APPLICATION OR CLICKING ON THE “I
                    ACCEPT” BUTTON OR USING THIS APPLICATION, OR OTHERWISE
                    HAVING ACCESS TO, RECEIVING, AND/OR USING THE APPLICATION,
                    YOU HEREBY CONFIRM TO HAVE READ, UNDERSTOOD AND AGREE TO BE
                    GOVERNED AND BOUND BY, THIS EULA, AND THE PRIVACY POLICY
                    WHICH IS INCORPORATED BY REFERANCE AND FORMS PART OF EULA
                    AND ANY OTHER RULES OR GUIDELINES, AS MAY BE ISSUED BY DPL
                    WITH RESPECT TO THE APPLICATION, FROM TIME TO TIME. YOU MAY
                    ACCESS THE PRIVACY POLICY HERE:{" "}
                    <span>insert link for privacy policy</span>. IF YOU DO NOT
                    AGREE TO BE BOUND BY THE EULA, PLEASE DO NOT CLICK THE “I
                    ACCEPT” BUTTON OR DOWNLOAD OR INSTALL THE APPLICATION AND
                    USE.{" "}
                  </p>
                </li>
                <li>
                  <p>
                    This EULA is deemed to be published and shall be construed
                    in accordance with the provisions of Rule 3 (1) of the
                    Information Technology (Intermediaries guidelines) Rules,
                    2011 under Information Technology Act, 2000 that require
                    publishing the rules and regulations, privacy policy and
                    user agreement for access or usage of the Content.
                  </p>
                </li>
                <li>
                  <p>For the purpose of this EULA:</p>
                </li>
              </ol>
              <p>
                5.1 &quot;Application&quot; means the mobile application made
                available to
              </p>
              <ol>
                <li>
                  <p>initiate communication with your saved contacts;</p>
                </li>
                <li>
                  <p>
                    receive communications from other users of the Application;
                  </p>
                </li>
                <li>
                  <p>
                    translate instant messages in other language to preferred
                    language of the user; and
                  </p>
                </li>
                <li>
                  <p>initiate and join multi-party audio-video conferencing.</p>
                </li>
              </ol>
              <p>5.2 &quot;Services&quot; means</p>
              <ol>
                <li>
                  <p>
                    provision of Application for initiating and receiving
                    communication with your saved contacts;
                  </p>
                </li>
                <li>
                  <p>
                    know approximate location of your saved contacts subject to
                    such contact enabling the features of the Application;
                  </p>
                </li>
                <li>
                  <p>
                    receiving short messaging services (&quot;SMS&quot;) from
                    others users of the Application;
                  </p>
                </li>
                <li>
                  <p>translating messages in preferred language of the user;</p>
                </li>
                <li>
                  <p>
                    access to third party services through their partnered
                    channels;
                  </p>
                </li>
                <li>
                  <p>multi-party HD quality video conferencing;</p>
                </li>
                <li>
                  <p>instant and scheduled invites to video conferencing;</p>
                </li>
                <li>
                  <p>
                    invite by various means such as (a) email; (b) SMS; (c)
                    third party messaging services installed in the user’s
                    Device (herein after defined);
                  </p>
                </li>
                <li>
                  <p>
                    allows invitees to join the conference through the
                    Application installed in any compatible Device or through
                    any compatible web browser installed in a laptop/desktop;
                  </p>
                </li>
                <li>
                  <p>
                    rich communication services involving (a) messaging
                    services, where a user can simultaneously send messages and
                    also display images, contacts and location through screen
                    sharing services; (b) file sharing services, where a user
                    can share files with third parties; and (c) chat services,
                    including group chatting (collectively “Rich Communication
                    Services” or “RCS”); and
                  </p>
                </li>
                <li>
                  <p>
                    any other service as may be provided by the Company from
                    time to time (collectively known as “Services”) on any
                    compatible smart phones powered by Android, Microsoft
                    windows or iOS; (“Device”).
                  </p>
                </li>
              </ol>
              <p>
                5.3 “Content” shall include all visual works, including all
                interactive content, texts, photographs, stickers etc., made
                available to you through the Application. The Content is owned
                by the Company or by third party content providers and licensed
                to the Company. Subject to your strict and full compliance with
                the EULA, the Company, hereby grants you a personal, limited,
                non-exclusive, non-transferable, revocable license to use the
                Content for your private and personal use through your Device.
              </p>
              <p>
                5.4 “Third Party Service Provider” shall include all the person
                or entities whose services or platforms are used by the Company
                to provide its services.
              </p>
              <p>
                6. In order to access the Application, you will be required to
                download and install the Application on your smart phone powered
                by Android/iOS.
              </p>
              <p>
                7. For disclosures relating to the collection and use of your
                personal information arising out of the use of this Application,
                please refer to the privacy policy available at{" "}
                <span>insert privacy policy link</span>.{" "}
              </p>
              <p>
                8. Modifications of T&amp;C: The Company reserves the right to
                change the EULA under which the Services are offered, including
                but not limited to the charges, if any, associated with the use
                of the Services. This EULA may be further modified based on
                changes in the business, legal and regulatory requirements and
                will be updated online. We will make all efforts to communicate
                any significant changes to this EULA to you. You are encouraged
                to periodically visit this page to review the EULA and any
                changes to it
              </p>
              <p>
                9. Modification of Services: The Company reserves the right to
                add, modify or delete any content or features available in the
                Services at any time at its sole discretion. At any point of
                time and without any intimation to users, the Company reserves
                the right to make any of its service a paid service.
              </p>
              <p>
                10. The Services offered by the Application are intended solely
                for the purpose of initiating and receiving communication with
                your saved contacts and such other services mentioned under
                Services. Unless otherwise specified, the Application is for
                your personal and non-commercial use. You may not modify, copy,
                distribute, transmit, display, perform, reproduce, publish,
                license, create derivative works from, transfer, or sell any
                information, software, products or Services obtained from the
                Application.
              </p>
              <p>
                11. The Application may contain links to or feeds from other web
                sites/applications (&quot;Linked Sites&quot;). The Linked Sites
                are not under the control of the Company and the Company is not
                responsible for the contents of any Linked Site, including
                without limitation any link contained in a Linked Site, or any
                changes or updates to a Linked Site or any information
                transmitted on a Linked Site. The inclusion of any link does not
                imply endorsement by the Company of the site or any association
                with its operators.
              </p>
              <p>
                12. Any dealings with third parties (including advertisers)
                included within or available via a link from the Application or
                participation in promotions, including the delivery of and the
                payment for goods and services, and any other terms, conditions,
                warranties or representations associated with such dealings or
                promotions, are solely between you and the advertiser or other
                third party. The Company shall not be responsible or liable for
                any part of any such dealings or promotions.
              </p>
              <p>
                13. The Application is owned by DPL or by a third-party and
                licensed to DPL. Subject to your strict and full compliance with
                the EULA, DPL, hereby grants you a personal, limited,
                non-exclusive, non-transferable, revocable license to use the
                Application for your private and personal use. As a condition of
                your use of the Application, you warrant to the Company that you
                will not use the Application for any purpose that is unlawful or
                prohibited by this EULA. You may not use the Application in any
                manner which could damage, disable, overburden or impair the
                Services.
              </p>
              <p>
                14. You are not entitled to use any kind of measures, mechanisms
                or tools (software or hardware) that could interfere with the
                functioning of the Application, the Jio Device or any of the
                Services thereunder.
              </p>
              <h5>15. LIABILITY DISCLAIMER</h5>
              <ol>
                <li>
                  <p>
                    THE COMPANY AND/OR ITS RESPECTIVE AFFILIATES MAKES NO
                    REPRESENTATIONS ABOUT THE COMPATIBILITY, SUITABILITY,
                    RELIABILITY, AVAILABILITY, TIMELINESS AND ACCURACY OF THE
                    INFORMATION, SOFTWARE AND SERVICES CONTAINED ON THE
                    APPLICATION FOR ANY PURPOSE. ALL SUCH INFORMATION, SOFTWARE
                    AND SERVICES ARE PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY
                    OF ANY KIND. THE COMPANY AND/OR ITS RESPECTIVE SUPPLIERS
                    HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH REGARD
                    TO THIS INFORMATION, SOFTWARE, AND SERVICES, INCLUDING ALL
                    IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY,
                    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
                    NON-INFRINGEMENT.
                  </p>
                </li>
                <li>
                  <p>
                    YOU SPECIFICALLY AGREE THAT THE COMPANY SHALL NOT BE
                    RESPONSIBLE FOR UNAUTHORISED ACCESS TO OR ALTERATION OF YOUR
                    TRANSMISSIONS OR DATA, ANY MATERIAL OR DATA SENT OR RECEIVED
                    OR NOT SENT OR RECEIVED, OR ANY TRANSACTIONS ENTERED INTO
                    THROUGH THE APPLICATION.
                  </p>
                </li>
                <li>
                  <p>
                    YOU SPECIFICALLY AGREE THAT THE COMPANY IS NOT RESPONSIBLE
                    OR LIABLE FOR ANY INFRINGEMENT OF ANOTHER&apos;S RIGHTS,
                    INCLUDING INTELLECTUAL PROPERTY RIGHTS. YOU SPECIFICALLY
                    AGREE THAT THE COMPANY IS NOT RESPONSIBLE FOR ANY SERVICES
                    SENT USING AND/OR INCLUDED IN THE APPLICATION BY ANY THIRD
                    PARTY.
                  </p>
                </li>
                <li>
                  <p>
                    THE COMPANY DOES NOT GUARANTEE COMPATIBILITY WITH ALL
                    OPERATING SYSTEMS, SMART PHONES, NETWORKS, INCLUDING ALL
                    VERSIONS OF THEM. THE USE OF THE SMART PHONE, SITE, AND
                    SOFTWARE, AND AUTOMATIC UPGRADES OF THE SOFTWARE, MAY
                    REQUIRE UPGRADES TO COMPUTER OR SMART PHONE OPERATING
                    SYSTEMS, NETWORKS, AND APPLICATION SOFTWARE.
                  </p>
                </li>
                <li>
                  <p>
                    ANY REQUIREMENTS FOR THE FUNCTIONING OF THE APPLICATION ON
                    YOUR PHONE OR DEVICE, SUCH AS SUFFICIENT BATTERY BACK UP,
                    INTERNET NETWORK STRENGTH ETC. IS YOUR SOLE RESPONSIBILITY.
                  </p>
                </li>
                <li>
                  <p>
                    IN NO EVENT SHALL THE COMPANY AND/OR ITS AFFILIATES BE
                    LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL,
                    SPECIAL, CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER
                    INCLUDING, WITHOUT LIMITATION, DAMAGES FOR OR IN RELATION TO
                    THE PROVISION OF OR FAILURE TO PROVIDE SERVICES, OR FOR ANY
                    INFORMATION, SOFTWARE AND SERVICES OBTAINED THROUGH THE
                    APPLICATION, OR OTHERWISE ARISING OUT OF THE USE OF, WHETHER
                    BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR
                    OTHERWISE, EVEN IF THE COMPANY OR ANY OF ITS SUPPLIERS HAS
                    BEEN ADVISED OF THE POSSIBILITY OF DAMAGES.
                  </p>
                </li>
                <li>
                  <p>
                    THE COMPANY USES THIRD PARTY PLATFORM TO PROVIDE ITS
                    SERVICES. YOU AGREE THAT THE COMPANY SHALL NOT BE LIABLE FOR
                    ANY BREACH OF LAW OR PRIVACY DONE BY SUCH THIRD PARTY.
                  </p>
                </li>
                <li>
                  <p>
                    THE TRANSLATION SERVICE CONTAIN TRANSLATIONS POWERED BY
                    THIRD PARTY. THIRD PARTY DISCLAIMS ALL WARRANTIES RELATED TO
                    THE TRANSLATIONS, EXPRESS OR IMPLIED, INCLUDING ANY
                    WARRANTIES OF ACCURACY, RELIABILITY, AND ANY IMPLIED
                    WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
                    PURPOSE AND NONINFRINGEMENT. <br />
                    <br /> The instant messages on this Application are
                    translated for your convenience using translation Artificial
                    Intelligence and Neural Machine Translation services powered
                    by Third Party Service Provider and aggregated for your use.
                    Reasonable efforts have been made to provide an accurate
                    translation; however, no automated translation is perfect
                    nor is it intended to replace human translators.
                    Translations are provided as a service to users of this
                    Application, and are provided &quot;as is.&quot; No warranty
                    of any kind, either expressed or implied, is made as to the
                    accuracy, reliability, or correctness of any translations
                    made from original language used by the sender of instant
                    message into any other language. Translated messages are not
                    saved in your device and thus cannot be forwarded or copied.{" "}
                    <br />
                    <br /> The primary text is the original language used by the
                    sender of instant message. Any discrepancies or differences
                    created in the translation are not binding and have no legal
                    effect for compliance or enforcement purposes. If any
                    questions arise related to the accuracy of the information
                    contained in the translated website, refer to the original
                    language used by the sender of instant message.
                  </p>
                </li>
              </ol>
              <p>
                16. The Company reserves the right to blacklist, disable and
                terminate that user from further using the Application or its
                Services. If the Company disables access to your account in
                accordance with the EULA (for example if you violate any
                applicable terms), you may be prevented from accessing the
                Application, your account details and/or any files and/or other
                Services that is stored with your account. The Company reserves
                the right, at its sole discretion, to terminate your access to
                any or all Services of the App and the related Services or any
                portion thereof at any time, without notice.{" "}
              </p>
              <p>
                17. Registration: Any person who wants to use the services of
                the Application, need to register on the Application by
                providing requisite details. You promise to provide us with
                accurate, complete, and updated registration information about
                yourself, where ever necessary. You may not transfer your
                account to anyone else without our prior written permission.
              </p>
              <p>
                18. Accuracy of Information: You agree that the information
                entered by you while profile creation/ updation or using any of
                Services is true, current, complete and accurate in all
                respects. The Company is not responsible for any losses arising
                out of discrepancy in your data. You are solely responsible for
                maintaining confidentiality and security of your user account
                and for all activities that occur on or through your user
                account. The Company is not responsible for any losses arising
                out of the unauthorized use of your user account.
              </p>
              <p>
                19. Use Restriction: You must not access the Application if you
                are a person who is either barred or otherwise legally
                prohibited from receiving or using the Service or any Services
                under the laws of India.
              </p>
              <p>
                20. DPL is free at its sole discretion to use any comments,
                information, ideas, concepts, reviews, or techniques or any
                other material contained in any communication you may send to us
                (&quot;User Feedback&quot;), including responses to
                questionnaires or through postings to the Application and user
                submissions, without further compensation, acknowledgement or
                payment to you for any purpose whatsoever including, but not
                limited to, developing, manufacturing and marketing products and
                creating, modifying or improving the DPL&apos;s service offering
                including Application. By posting / submitting any User Feedback
                / user content/ user submission on the Application, You grant
                DPL a perpetual, worldwide, non-exclusive, royalty-free
                irrevocable, sub-licensable license and right in such User
                Feedback /user content/ user submission to DPL, including the
                right to display, use, reproduce, or modify the User Feedback /
                user content/ user submission in any media, software or
                technology of any kind now existing or developed in the future.
                DPL reserves the right to remove User Feedback / user content/
                user submission at sole discretion and/or upon on request of any
                third party that such User Feedback / user content/ user
                submission may create liability for DPL or harm the reputation
                of DPL or are offensive, inappropriate, defamatory, obscene or
                libelous in nature.
              </p>
              <p>
                21. Third-Party Fees: You may incur access or data fees from
                third parties (such as your internet provider or mobile carrier)
                in connection with your use of Services and of Application. You
                are solely responsible for all such fees. In other words, the
                Company is not responsible for such fees, availability or
                non-availability of any third-party services and any
                corresponding loss of Services.
              </p>
              <p>
                22. Updates: You may need to install updates to the Application
                or related software that we introduce from time to time to use
                of the Application. Services originating from the Application
                may communicate with the servers from time to time to check for
                available updates to the Services and to the functionality of
                the Application, such as bug fixes, patches, enhanced functions,
                missing plug-ins and new versions (collectively,
                &quot;Updates&quot;). Your use of the Services you have
                installed requires that you have agreed to receive such
                automatically requested Updates. The terms of this EULA will
                govern any Upgrades, updates, modifications or enhancements to
                the Application.
              </p>
              <p>
                23. Where you download the Application on a device and from an
                application store of any specific operating system, you shall be
                obligated to adhere to all the terms and conditions of the use
                of such device, the terms and conditions of the relevant
                application store maintained by such operating system, in
                addition to this EULA. For avoidance of any doubt, the Company
                shall not be responsible for any losses arising out of or in
                connection with this EULA for any failures, acts or omissions by
                you of the Application to comply with the terms and conditions
                for the use of such device.
              </p>
              <p>
                24. The Company or all the right holders in/of the Application
                and/or your smart phone/tablet, as the case may be, own title,
                interest and rights, including all related intellectual property
                rights, in/of the Application and/or your smart phone/tablet and
                the user acknowledges that such ownership shall include all
                intellectual property rights arising from any suggestions,
                enhancement requests, recommendations or other information
                provided by the user, whether in the course of use of the
                Application, your smart phone/tablet or otherwise.
              </p>
              <p>
                25. Where any particular term or provision of this EULA is
                determined under applicable law to be un-enforceable, such
                un-enforceable term(s) shall be severed from and will not affect
                any other terms and conditions. The Company reserves the right
                to substitute any such un-enforceable term or provision with a
                suitable and enforceable provision at its sole discretion.
              </p>
              <p>
                26. All disputes shall be governed under the laws of India and
                are subject to the jurisdiction of the Courts of{" "}
                <span>Ahmedabad </span> only.{" "}
              </p>
              <p>
                27. If you have questions or concerns about this policy, please
                contact at <span>insert customer care email address</span> Last
                Updated: <span>insert date of uploading this document</span>.
                Copyright © 2021, DPL. All rights reserved.{" "}
              </p> */}
            </div>
            {/* {loading ? (
              <GlobalLoader />
            ) : (
              <>
                <div className="heading">
                  <h3 className="heading_sub font-ad">Agreement</h3>
                  <h1 className="heading_main">
                    End User License Agreement Daakia
                  </h1>
                </div>
                <div className="cmsPage">
                  <ol>
                    <li>
                      <p>{userAgreementData}</p>
                    </li>
                  </ol>
                </div>
              </>
            )} */}
          </div>
        </Container>
      </section>
    </>
  );
}

export default CookiesPolicy;
